export const experience=[['NatWest Group','Software Engineer, AVP','Oct 2025 — Present','Own frontend delivery for a UK banking onboarding platform. Built role-aware dashboards, KYC/AML workflows, exception analysis and SLA visibility.'],['Capgemini','Senior Application Consultant','Jun 2021 — Sep 2025','Delivered IKEA operations workflows and Volvo diagnostic experiences. Improved page loads by 40% and reduced regression issues by 60%.'],['Tata Consultancy Services','Assistant Consultant','Jun 2016 — May 2021','Engineered PayPal recurring payments, Ageas insurance journeys and Apple vendor-management and anti-fraud interfaces.'],['Ness Technologies','Software Engineer','Feb 2014 — Jun 2016','Created reusable interfaces for GE Capital across Energy, Aviation and Healthcare.']] as const;
export const projects=[['NatWest Onboarding','Banking & Compliance','KYC / AML · RBAC dashboards · SLA intelligence'],['PayPal Autopay','Payments','Recurring payments · Enterprise integration'],['Ageas Home Insurance','Insurance','Dynamic quotes · Policy issuance'],['IKEA Flexa Admin','Enterprise Operations','Pricing workflows · Power BI analytics'],['Volvo Diagnostics','Automotive','Vehicle health · Global platform']] as const;
export const skills={Frontend:['React','Next.js','TypeScript','JavaScript','Tailwind CSS','SCSS'],'State & APIs':['Redux Toolkit','RTK Query','React Query','GraphQL','REST APIs','Node.js'],Quality:['Jest','React Testing Library','TDD','Mocha','WCAG 2.1 AA'],Platform:['GitHub Actions','CI/CD','Docker','AWS','Azure','Vite'],Domain:['Banking onboarding','KYC / AML','RBAC','SLA / TAT','Payments','Insurance']};

export type ChatAnswer = { id: string; question: string; answer: string; keywords: readonly string[] };

export const chatAnswers: readonly ChatAnswer[] = [
  { id: 'react', question: 'What is Raju’s React experience?', answer: 'Raju is a Senior Frontend Engineer with over a decade of frontend experience. His frontend toolkit includes React, Next.js, TypeScript, JavaScript, Tailwind CSS and SCSS. He has built secure enterprise interfaces across banking, payments, insurance, retail operations, automotive diagnostics and vendor-management products.', keywords: ['react', 'frontend experience', 'typescript experience', 'next.js', 'nextjs'] },
  { id: 'banking', question: 'What banking experience does Raju have?', answer: 'At NatWest Group, Raju owns frontend delivery for a UK banking onboarding platform. His work includes role-aware dashboards, KYC/AML workflows, exception analysis and SLA visibility. His domain skills also include RBAC, SLA/TAT, payments and insurance.', keywords: ['banking', 'bank', 'fintech', 'natwest', 'kyc', 'aml', 'compliance', 'rbac'] },
  { id: 'projects', question: 'Which projects has Raju worked on?', answer: 'Selected work includes NatWest Onboarding, PayPal Autopay, Ageas Home Insurance, IKEA Flexa Admin and Volvo Diagnostics. These cover banking and compliance, recurring payments, insurance quotes and policy issuance, pricing and analytics workflows, and vehicle-health diagnostics.', keywords: ['project', 'work', 'portfolio', 'paypal', 'ageas', 'ikea', 'volvo'] },
  { id: 'skills', question: 'What are Raju’s core skills?', answer: 'Raju’s skills include React, Next.js, TypeScript, JavaScript, Redux Toolkit, RTK Query, React Query, GraphQL, REST APIs, Node.js, Jest, React Testing Library, TDD, GitHub Actions, Docker, AWS, Azure and Vite. He also lists WCAG 2.1 AA and CI/CD among his quality and platform skills.', keywords: ['skill', 'technology', 'technologies', 'tech stack', 'expertise', 'tools'] },
  { id: 'availability', question: 'Is Raju available for opportunities?', answer: 'Raju’s portfolio states that he is available for impactful opportunities and invites enquiries about senior frontend, lead UI or fintech engineering roles. He is currently building at NatWest Group.', keywords: ['available', 'availability', 'opportunity', 'opportunities', 'role', 'hire', 'hiring'] },
  { id: 'contact', question: 'How can I contact Raju?', answer: 'You can contact Raju at rajuerladinny@gmail.com or through LinkedIn at linkedin.com/in/rajuerladinny. He is based in Bengaluru, India.', keywords: ['contact', 'email', 'linkedin', 'reach', 'location', 'bengaluru'] },
] as const;

export const chatFallback = 'I can only answer from Raju’s portfolio. Try asking about his React experience, banking experience, projects, skills, availability or contact details.';
